In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [5]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
scores_logistic =[]
scores_svm =[]
scores_rf =[]
for train_index,test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(gamma='auto'),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))


In [6]:
scores_logistic

[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]

In [7]:
scores_svm

[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]

In [8]:
scores_rf

[0.9385382059800664, 0.9365609348914858, 0.9211409395973155]

In [10]:
from sklearn.model_selection import cross_val_score

In [11]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=3)

array([0.89534884, 0.94991653, 0.90939597])

In [12]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)

array([0.39368771, 0.41068447, 0.45973154])

In [13]:
cross_val_score((RandomForestClassifier(n_estimators = 40)),digits.data,digits.target,cv=3)

array([0.94518272, 0.94323873, 0.91946309])

In [14]:
scores_1 = cross_val_score((RandomForestClassifier(n_estimators = 5)),digits.data,digits.target,cv=10)
np.average(scores_1)

0.8758158841812597

In [ ]:
scores_2 = cross_val_score((RandomForestClassifier(n_estimators = 5)),digits.data,digits.target,cv=10)
np.average(scores_1)