In [68]:
import pandas as pd
import numpy as np
from sklearn import linear_model 

In [69]:
address = "C:\\Users\Home-PC\\Desktop\\happy\\homeprices.xlsx"
#dir(pd)
df = pd.read_excel(address)
df.columns=['area','bedrooms','age','price']
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [70]:
df.bedrooms.median()

4.0

In [71]:

df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())

In [58]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [72]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [73]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [74]:
reg.intercept_

221323.00186540443

In [75]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [76]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In [77]:
reg.score(df[['area','bedrooms','age']],df.price)

0.9550196399325819

In [78]:
import pickle

In [86]:
with open("C:\\Users\\Home-PC\\Desktop\\happy\\reg_pickle",'wb') as file:
    pickle.dump(reg, file)

In [88]:
with open("C:\\Users\\Home-PC\\Desktop\\happy\\reg_pickle",'rb') as file:
    mp = pickle.load(file)

In [89]:
mp.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [90]:
mp.intercept_

221323.00186540443

In [91]:
mp.predict([[3000,3,0]])

array([627676.96792563])

In [92]:
from sklearn.externals import joblib

c:\program files\python37\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [93]:
joblib.dump(reg,'reg_joblib')

['reg_joblib']

In [94]:
mj = joblib.load('reg_joblib')

In [95]:
mj.intercept_

221323.00186540443

In [96]:
mj.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [97]:
mj.predict([[2000,3,5]])

array([499455.93644033])